name: Build Geode Mod

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          sdk: given
          target: Win64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: reclick-geode
          path: ${{ steps.build.outputs.build-output }}
